runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /.*
  script: randomsheetmusic.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: latest
- name: setuptools
  version: latest

